"""empty message

Revision ID: 769fc6d12950
Revises: 52853f484399
Create Date: 2022-06-01 01:05:29.795477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "769fc6d12950"
down_revision = "52853f484399"
branch_labels = None
depends_on = None

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        # sa.Column("user", sa.Integer(), nullable=False),
        # sa.Column("post", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["post_id"],["posts.id"]),
        sa.ForeignKeyConstraint(["user_id"],["users.id"]),
        # sa.ForeignKeyConstraint(["user"], ["post.id"]),
        # sa.ForeignKeyConstraint(["post"], ["post.id"]),
        sa.PrimaryKeyConstraint("id")
        )

    if environment == "production":
        op.execute(f"ALTER TABLE comments SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    # ### end Alembic commands ###
