"""post model

Revision ID: 52853f484399
Revises: 64d53bed114c
Create Date: 2022-05-31 20:26:20.909292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52853f484399"
down_revision = "64d53bed114c"
branch_labels = None
depends_on = None

import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("img_url", sa.String(length=255), nullable=False),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"],["users.id"]),
        sa.PrimaryKeyConstraint("id")
        )

    if environment == "production":
        op.execute(f"ALTER TABLE posts SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    # ### end Alembic commands ###
